name: Build Android APK
on: [push]

jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Create .love file
        run: |
          git archive --format=zip -o game.love HEAD
          unzip -l game.love | head -20   # main.lua should be at the root

      - name: Build Android APK
        uses: love-actions/love-actions-android@v2
        with:
          app-name: "Zombie Seige Beta V5"
          bundle-id: "com.love2d.zombieseige"
          resource-path: "./android-res"
          love-package: "./game.love"

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: "**/*.apk"
